[ballerinax.wso2.controlplane]
keyStorePath = "<path-to-keystore>"

[ballerinax.wso2.controlplane.dashboard]
url = "https://localhost:9743/dashboard/api"
heartbeatInterval = 10
groupId = "ballerina_group"
nodeId = "ballerina_dev_node"
mgtApiUrl ="https://localhost:9164/management/"
