# [ballerinax.wso2.controlplane]
# keyStorePath = "<path-to-keystore>"
# trustStorePath = "<path-to-truststore>"
# icpServicePort = 9264

[ballerinax.wso2.controlplane.dashboard]
url = "https://localhost:9743/dashboard/api"
heartbeatInterval = 10
groupId = "group1"
mgtApiUrl ="https://localhost:9264/management/"
# nodeId = "node_1"
# serviceAccount = "bal_admin"
# serviceAccountPassword = "bal_secret"
